# VPC
# cn-beijing
output "vpc_id_beijing" {
    description = "Id of VPC in cn-beijing region"
    value = module.opencbdc_tctl.vpc_id_beijing
}
output "public_subnets_beijing" {
    description = "Public subnet Ids associated with VPC in cn-beijing region"
    value = module.opencbdc_tctl.public_subnets_beijing
}
output "private_subnets_beijing" {
    description = "Private subnet Ids associated with VPC in cn-beijing region"
    value = module.opencbdc_tctl.private_subnets_beijing
}
output "azs_beijing" {
    description = "Availability zones used by VPC located in cn-beijing region"
    value = module.opencbdc_tctl.azs_beijing
}
output "vpc_interface_endpoint_beijing" {
    description = "VPC interface endpoint associated with VPC in cn-beijing region"
    value = module.opencbdc_tctl.vpc_interface_endpoint_beijing
}
# cn-hangzhou
output "vpc_id_hangzhou" {
    description = "Id of VPC in cn-hangzhou region"
    value = module.opencbdc_tctl.vpc_id_hangzhou
}
output "public_subnets_hangzhou" {
    description = "Public subnet Ids associated with VPC in cn-hangzhou region"
    value = module.opencbdc_tctl.public_subnets_hangzhou
}
output "private_subnets_hangzhou" {
    description = "Private subnet Ids associated with VPC in cn-hangzhou region"
    value = module.opencbdc_tctl.private_subnets_hangzhou
}
output "azs_hangzhou" {
    description = "Availability zones used by VPC located in cn-hangzhou region"
    value = module.opencbdc_tctl.azs_hangzhou
}
output "vpc_interface_endpoint_hangzhou" {
    description = "VPC interface endpoint associated with VPC in cn-hangzhou region"
    value = module.opencbdc_tctl.vpc_interface_endpoint_hangzhou
}
# cn-shanghai
output "vpc_id_shanghai" {
    description = "Id of VPC in cn-shanghai region"
    value = module.opencbdc_tctl.vpc_id_shanghai
}
output "public_subnets_shanghai" {
    description = "Public subnet Ids associated with VPC in cn-shanghai region"
    value = module.opencbdc_tctl.public_subnets_shanghai
}
output "private_subnets_shanghai" {
    description = "Private subnet Ids associated with VPC in cn-shanghai region"
    value = module.opencbdc_tctl.private_subnets_shanghai
}
output "azs_shanghai" {
    description = "Availability zones used by VPC located in cn-shanghai region"
    value = module.opencbdc_tctl.azs_shanghai
}
output "vpc_interface_endpoint_shanghai" {
    description = "VPC interface endpoint associated with VPC in cn-shanghai region"
    value = module.opencbdc_tctl.vpc_interface_endpoint_shanghai
}

# ECS
# cn-beijing
output "ecs_cluster_id" {
    description = "ECS cluster id"
    value = module.opencbdc_tctl.ecs_cluster_id
}
output "ecs_cluster_name" {
    description = "ECS cluster name"
    value = module.opencbdc_tctl.ecs_cluster_name
}

# DNS
output "dns_endpoints" {
    description = "DNS endpoints generated by test controller services"
    value = module.opencbdc_tctl.dns_endpoints
}
